<form method="post" action="{DIR}student/{CASE}/{ID}">
	<table>
		<tr>
			<td>Studentnummer</td>
			<td>{STUDENTNR}</td>
		</tr>
		<tr>
			<td>Voornaam</td>
			<td>{VOORNAAM}</td>
		</tr>
		<tr>
			<td>Tussenvoegsel</td>
			<td>{TS}</td>
		</tr>
		<tr>
			<td>Achternaam</td>
			<td>{ACHTERNAAM}</td>
		</tr>
		<tr>
			<td>Adres</td>
			<td>{ADRES}</td>
		</tr>
		<tr>
			<td>Postcode</td>
			<td>{POSTCODE}</td>
		</tr>
		<tr>
			<td>Plaats</td>
			<td>{PLAATS}</td>
		</tr>
		<tr>
			<td>Email</td>
			<td>{EMAIL}</td>
		</tr>
		<tr>
			<td>Telefoonnummer</td>
			<td>{TN}</td>
		</tr>
		<tr>
			<td><a href="{DIR}student/"><input type='button' value='Terug' /></a></td>
			<td><input type='submit' value='Edit' /></td>
		</tr>
	</table>
</form>