<div class="content">
    <form method="post" id="editForm" action="<?php echo $this->baseDir; ?>user/edit/<?php echo $this->get['id']; ?>">
        <div class="form-group">
            <label for="email">E-mailadres</label>
            <input type="email" class="form-control" id="email" name="email" placeholder="E-mailadres" oninput="validateEmail(this)">
        </div>
        <div class="form-group">
            <label for="firstname">Voornaam</label>
            <input type="text" class="form-control" id="firstname" name="firstname" placeholder="Voornaam">
        </div>
        <div class="form-group">
            <label for="lastname">Achternaam</label>
            <input type="text" class="form-control" id="lastname" name="lastname" placeholder="Achternaam">
        </div>
        <div class="form-group">
            <label for="password">Wachtwoord</label>
            <input type="password" class="form-control" id="password" name="password" placeholder="Wachtwoord">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
    </form>
</div>

<script>
    $(document).ready(function() {
		var json = <?php echo $this->content; ?> ;
		console.log(json);

        $("#email").val(json.email);
        $("#firstname").val(json.first_name);
        $("#lastname").val(json.last_name);
        $("#password").val(json.password);
    });

    // API-04/nieuwe API-03
    function validateField(pattern,string) {
        return (pattern.test(string));
    }

    function validateEmail(input) {
        //console.log(input.id);
        //console.log(validateField(/^([A-z0-9._-]+@{1}[A-z0-9]+.{1}[A-z]{2,})$/, input.value));

        if (validateField(/^([A-z0-9._-]+@{1}[A-z0-9]+.{1}[A-z]{2,})$/, input.value) == false) {
            $('#helpEmail').remove();
            $('#email').parent().addClass('has-error');

            var help = '<span id="helpEmail" class="help-block">Voer alstublieft een geldig e-mailadres is.</span>';
            $('#email').parent().append(help);
        } else {
            $('#email').parent().removeClass('has-error');
            $('#helpEmail').remove();
        }
    }

    //var patt_email = new RegExp("/^([A-z0-9._-]+@{1}[A-z0-9]+.{1}[A-z]+)$/");
    //var patt_pass = /^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{8,}$/;

   /* $("input").on("blur", function() {
        var input = this.value;
        var type = this.type;

        if (!input) {
            console.log("dit veld mag niet leeg zijn");
        } else {
            if (type == "email") {

                if (input.search(patt_email)) {
                    console.log("email ok");
                } else {
                    console.log("Voer een geldig e-mailadres in!");
                    this.className += " error";
                }
            }

            if (type == "password") {
                if (input.search(patt_pass)) {
                    console.log("password ok");
                    console.log(input);

                } else {
                    console.log("Uw wachtwoord moet minstens 8 karakters lang zijn, waarvan tenmiste 1 cijfer, 1 kleine letter, 1 grote letter en 1 speciaal teken)");
                    this.className += " error";
                }
            }
        }
    }); */

    $("form").submit(function() {

    });
</script>
