<div class="content">
    <form method="post" action="<?php echo $this->baseDir; ?>user/saveEdit/<?php echo $this->get['id']; ?>">
        <div class="form-group">
            <label for="email">E-mailadres</label>
            <input type="email" class="form-control" id="email" placeholder="E-mailadres">
        </div>
        <div class="form-group">
            <label for="firstname">Voornaam</label>
            <input type="text" class="form-control" id="firstname" placeholder="Voornaam">
        </div>
        <div class="form-group">
            <label for="lastname">Achternaam</label>
            <input type="text" class="form-control" id="lastname" placeholder="Achternaam">
        </div>
        <div class="form-group">
            <label for="password">Wachtwoord</label>
            <input type="password" class="form-control" id="password" placeholder="Wachtwoord">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
    </form>
</div>

<script>
    $(document).ready(function() {
		var json = <?php  echo $this->content ?> ;
		console.log(json);

        $("#email").val(json.email);
        $("#firstname").val(json.first_name);
        $("#lastname").val(json.last_name);
        $("#password").val(json.password);
    });
</script>
